name: dollarfeeds
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #Gives a carousel with features such as autoplay and indicators
  carousel_slider: ^1.3.0

  # Cross-platform snackbars to display messages to the user
  flushbar: ^1.9.0

  # Bubble tab indicator
  bubble_tab_indicator: "^0.1.4"

  # Bottom nav bar UI
  bottom_navy_bar: ^5.2.0

  # Sliding up panel UI for map screen
  sliding_up_panel: ^0.3.6

  # Open URLs
  url_launcher: ^5.2.5

  # Star ratings for locations
  flutter_rating_bar: ^3.0.0

  # Make text smaller than a certain font size if necessary for it to fit
  auto_size_text: ^2.1.0

  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4

  # Display a Google Maps widget
  google_maps_flutter: ^0.5.21+7
  flutter_google_places: ^0.2.3

  # Get device location
  location: ^2.3.5

  http: ^0.12.0+1
  json_serializable: ^2.0.2

  path_provider: ^1.4.0

  # Get version number
  package_info: ^0.4.0+13

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # App assets
  assets:
    - assets/brand_logos/
    - assets/images/
    - assets/map/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
